# Site settings
title: Yet Another Jekyll Theme
email: mail@mail.com
name: ultra mollusk
description: 念念不忘 必有回响
url: https://toddlam.github.io/yajt/ # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title.html
paginate: 10

rss_url: /feed.xml
archive_url: /archive/
tags_url: /tags/
about_url: /about/
home_url: /index.html

# Build settings
# markdown: redcarpet

#Personal Info
author:
  name: 小弱鸡
  full_name: ToddLam
  link: https://toddlam.github.io/yajt/
  github: https://github.com/toddlam/
  email: toddylin@hotmail.com
  qq: 10086

#Disqus
disqus:
  url: xxx.disqus.com
